### ISSUE TITLE
No module named 'binance'

### ISSUE THREAD

**Issue by redboxx91** [fj317/PumpBot#1]
I get this error:

`Microsoft` Windows [Version 6.1.7601]

Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\VAIO>cd C:\Users\VAIO\Desktop\PumpBot-master

C:\Users\VAIO\Desktop\PumpBot-master>PumpBot.py
Traceback (most recent call last):
  File "C:\Users\VAIO\Desktop\PumpBot-master\PumpBot.py", line 1, in <module>
    from binance.client import Client
ModuleNotFoundError: No module named 'binance'

C:\Users\VAIO\Desktop\PumpBot-master>

is something missing or I'm doing something wrong?

**Comment by henyoapps** [comment]
Two things wrong here.. firstly, you're using a Sony.. who does that??

But seriously, read the readme to install this properly. It's all right there. You have to install the Python binance API. Then it will work.

**Comment by LUVhaxo** [comment]
@henyoapps Hey do you have discord or anything where I could contact you quickly?

**Comment by LUVhaxo** [comment]
@redboxx91 Did you get your problem sorted out?

**Comment by skydrow68** [comment]
You have this error because you didn't have installed sammchardy's Python Binance API.
