### ISSUE TITLE
PumpBot.py closes instantly

### ISSUE THREAD

**Issue by florent00** [fj317/PumpBot#10]
When I want to open PumpBot.py, it just closes instantly. It appears for not even a second and closes. 
I've downloaded everything you need to start the bot so that should not be the problem.

**Comment by skydrow68** [comment]
SImple question but, do you open PumpBot.py with the Terminal ? Or with a double click ?

**Comment by florent00** [comment]
double click, I have no experience so tell me if am doing something wrong xD

**Comment by fj317** [comment]
You should be starting the bot with the terminal with the command 'python3 PumpBot.py'.

**Comment by fj317** [comment]
Of course this will only work
