### ISSUE TITLE
Some improvements in reliability

### ISSUE THREAD

**Issue by lbosk** [fj317/PumpBot#103]
Hello
I read your code and I found some weakness in reliability. Therefore, I wounld like to propose some corrections.
1) during buy, you perform:
order = client.order_limit_buy(...)
while not(orderCompleted):
    pass

If the current price already went above averagePrice you will not be able to buy and you will end up buying during the dump. Therefore a timeout of N1 (programmable by config) seconds should be set up. If you exit by timeout, depending whether you was able to buy someting or not, the program should continue or stop

2) during sell, you set up an OCO order and then wait:
order = client.create_oco_order()
This is very dangerous too, because
a - you might not reach the roundedPriceToSell and not being able to sell on the top
b - during the dump, the buy book is almost depleted, so the price can easily drop below stopPrice in less than 1 second without you to be able to sell.
therefore:
a - here again a timeout of N2 (programmable by config) seconds should be set up. If you exit by timeout, marketSell(coinOrderQty)
b - the timeout saves you anyway, but is is better also to set the trigger point of the OCO above stopPrice. For instance
TriggerThreshold= (1+stopLoss)/2
triggerPrice = float_to_string(TriggerThreshold* coinPriceBought, int(- math.log10(minPrice)))
and then:
        stopPrice=triggerPrice,
        stopLimitPrice=stopPrice,

**Comment by fj317** [comment]
> 
>     1. during buy, you perform:
>        order = client.order_limit_buy(...)
>        while not(orderCompleted):
>        pass
> 
> 
> If the current price already went above averagePrice you will not be able to buy and you will end up buying during the dump. Therefore a timeout of N1 (programmable by config) seconds should be set up. If you exit by timeout, depending whether you was able to buy someting or not, the program should continue or stop

I'll look into adding a timeout feature but I have a lot of work currently so it may be a while before its implemented. Feel free to submit a pull request with the feature and I'll happily add it.

> 
>     2. during sell, you set up an OCO order and then wait:
>        order = client.create_oco_order()
>        This is very dangerous too, because
>        a - you might not reach the roundedPriceToSell and not being able to sell on the top
>        b - during the dump, the buy book is almost depleted, so the price can easily drop below stopPrice in less than 1 second without you to be able to sell.
>        therefore:
>        a - here again a timeout of N2 (programmable by config) seconds should be set up. If you exit by timeout, marketSell(coinOrderQty)
>        b - the timeout saves you anyway, but is is better also to set the trigger point of the OCO above stopPrice. For instance
>        TriggerThreshold= (1+stopLoss)/2
>        triggerPrice = float_to_string(TriggerThreshold* coinPriceBought, int(- math.log10(minPrice)))
>        and then:
>        stopPrice=triggerPrice,
>        stopLimitPrice=stopPrice,

I'm confused by the way you're calculating the triggerThreshold here. As above, if you are able to implement this feature, please submit a pull request and I'll take a look and merge the code bases if it works efficiently and effectively.

**Comment by lbosk** [comment]
I put requests #113 and #114 for point 1.
I was no able yet to test the situation of an order partially filled when the timeout happens.
Still working on point 2

**Comment by fj317** [comment]
Now implemented, closing issue.
