### ISSUE TITLE
Fiat currency different from USD

### ISSUE THREAD

**Issue by lbosk** [fj317/PumpBot#105]
Instead of using
in_USD = float((data['bpi']['UDS']['rate_float']))
it would be nice to decide the fiat currency from config.json

for instance in config
"fiatcurrency": "EUR",

and then
f = open('config.json', )
data = json.load(f)
...
fiatcurrency = data['fiatcurrency']
...
in_USD = float((data['bpi'][fiatcurrency]['rate_float']))

**Comment by fj317** [comment]
Thanks for the feature request, I'll take a look at implementing it next time I'm working on the code.

**Comment by lbosk** [comment]
Pull requests #107 and #108

**Comment by fj317** [comment]
Implemented into master build. Closing issue.
