### ISSUE TITLE
Account has insufficient balance

### ISSUE THREAD

**Issue by skydrow68** [fj317/PumpBot#11]
![Capture d’écran du 2021-02-13 20-24-33](https://user-images.githubusercontent.com/39465988/107859429-a841ae00-6e39-11eb-8db5-766b13e8f812.png)

Hy,

with a friend we try some settings. And we noticed this : 
As soon as the "percentOfWallet" is >50 , then the terminal send us this error message.

Presision : I have BNB and i use BNB for the fees.  My friend didn't use BNB and we have the same error 

Config.json : 
    "buyLimit": 1.85,
    "profitMargin": 200,
    "percentOfWallet": 70,
    "stopLoss": 0.50,
    "coinPair": "BTC",
    "getPastTrades": "TRUE"

**Comment by fj317** [comment]
I am unsure what could be causing this error. I've just completed an order for BNBBTC with 70% of my wallet and it worked fine. Are you running the latest code?

**Comment by skydrow68** [comment]
After test, i can say that the problem is causing by the "buyLimit"
with a buylimit of 1.85 this is not working.
with a buylimit of 1.15 this is working.

it is independent of the "true" or "false" of the getPastTrades

**Comment by fj317** [comment]
The buyLimit is the maximum price you are willing to pay for the coin therefore you must have enough funds to pay out in the case that you buy at the maximum value (1.85 in this case). 
With the new changes this is implemented whether getPastTrades is set to TRUE or FALSE. getPastTrades is used to change whether you want you want to use the market price at the time you entered the coin pair, or the average price of the coin over the last 2 minutes.
The readme has more information on this in the [config.json section](https://github.com/fj317/PumpBot#configjson)
