### ISSUE TITLE
Bot did not work properly

### ISSUE THREAD

**Issue by ernestonee** [fj317/PumpBot#15]
Welp the bot die Not wirklich on the BPS NEBL Pump total... kinda  the bot bought the coin like 1 min after i typed it in, so yeah i did Not Lose much,  but the bot didnt place the Buy order so Thats sad

**Comment by skydrow68** [comment]
Same...

**Comment by ezanchi** [comment]
I got this error
![error](https://user-images.githubusercontent.com/22500633/107863742-a209fc80-6e4e-11eb-8a9a-d2ddf57175fd.png)

**Comment by ernestonee** [comment]
for me it didnt even said that the buy order was made, i saw it on binance

**Comment by redboxx91** [comment]
I'm testing it right now and I get some errors related to API. - I can't find any details on the indicate link on Binance.
for example: "A BinanceAPI error has occured. Code = -1013"
Sometimes bot is working to a point (ex: buy order or/and sell order)  sometimes to is not even place the sell order.
GraphModule.py - is generating the recent_trades.csv file with last 10 sec prices...but I can't understand it...

**Comment by ernestonee** [comment]
Ok i think i know now what Was my Problem, i had get past trades on so i think this is why it took a while

**Comment by fj317** [comment]
The bot is a work in progress as stated in the readme so these errors aren't surprising. I'll try and fix them, however it is difficult when I cannot replicate the errors myself. Please follow the new issue bug report template to report bugs in order to help us fix the errors as easily and quickly as possible.

**Comment by ezanchi** [comment]
> The bot is a work in progress as stated in the readme so these errors aren't surprising. I'll try and fix them, however it is difficult when I cannot replicate the errors myself. Please follow the new issue bug report template to report bugs in order to help us fix the errors as easily and quickly as possible.

It could create a .log file that logged what is happening for better troubleshooting.
