### ISSUE TITLE
Different Ways of Entering Amount

### ISSUE THREAD

**Issue by ezanchi** [fj317/PumpBot#16]
Enter USDT and have it calculate BTC or enter BTC directly and also percentage of total.

**Comment by fj317** [comment]
I'll add ability enter BTC directly in the config.json but I don't see the point in using USDT.

**Comment by ezanchi** [comment]
I have some Python knowledge. It is not much but I think I can contribute to the project. If you want you can assign me this task and I will do it.

**Comment by fj317** [comment]
Sure thing thanks!

**Comment by ezanchi** [comment]
> Sure thing thanks!

So would it be BTC only or both BTC and percentage of wallet?

**Comment by fj317** [comment]
> > Sure thing thanks!
> 
> 
> 
> So would it be BTC only or both BTC and percentage of wallet?

I think we should have it so the user uses percentage of wallet normally, however if they enter an exact amount of btc (to another config variable called 'BTCAmount' for example) it overrides the percent of wallet amount.

**Comment by ezanchi** [comment]
> > > Sure thing thanks!
> > 
> > 
> > So would it be BTC only or both BTC and percentage of wallet?
> 
> I think we should have it so the user uses percentage of wallet normally, however if they enter an exact amount of btc (to another config variable called 'BTCAmount' for example) it overrides the percent of wallet amount.

Done. Pretty basic but functional.

**Comment by fj317** [comment]
Merged into master branch so now closed.
