### ISSUE TITLE
Take-Profit Strategy

### ISSUE THREAD

**Issue by ezanchi** [fj317/PumpBot#18]
Take-Profit Strategies:

The take-profit strategies will determine how the amount will be divided between the targets by default when creating a trade. 

The bot offers the following take-profit strategies: 
**1. Evenly Divided** - When using this option, the bot will evenly divide the trade amount between the different take-profit targets. For example, when creating a trade with 4 take-profit targets, the bot will place 25% of the trade amount in each target.

**2. Fifty On First Target** - Using this option, the bot will place 50% of the trade amount on the first take-profit target, and will divide the other 50% equally among the remaining take- profit targets.

**3. Decreasing Exponential** - In this strategy, starting from the take-profit target with the lowest price, each target will have half the amount as the previous entry target, such that the first target has the largest percentage of the trade amount and the last target has the smallest percentage. 
The amount of percentages will be divided in a way such that their sum will still equal 100%. 
For example, when 4 take-profit targets are defined the first take-profit target with the lowest price will have 53.333% of the trade amount, the second target will have 26.666% (half the amount of the previous target), the third target will have 13.333% and the last take-profit target with the highest price will have 6.666% of the trade amount.

**4. Increasing Exponential** - In this strategy, starting from the take-profit target with the lowest price, each target will have twice the amount as the previous take-profit target, such that the first target has the smallest percentage of the trade amount and the last target has the largest percentage. 
The amount of percentages will be divided in a way such that their sum will still equal 100%. 
For example, when 4 take-profit targets are defined the first take-profit target with the lowest price will have 6.666% of the amount, the second target will have 13.333% (twice the amount of the previous target), the third target will have 26.666% and the last take-profit target with the highest price will have 53.333% of the trade amount.

**Comment by fj317** [comment]
Adding these strategies seems like too much work for too little gain.
In the future possibly we could improve the profit strategies but at the current moment there are more important improvements to be made.

**Comment by ezanchi** [comment]
> Adding these strategies seems like too much work for too little gain.
> In the future possibly we could improve the profit strategies but at the current moment there are more important improvements to be made.

The main benefit is that one could set many Target Prices to sell progressively and that way don't risk it so much for the "All or Nothing".
