### ISSUE TITLE
Trailing Take-Profit and Stop-Loss

### ISSUE THREAD

**Issue by ezanchi** [fj317/PumpBot#19]
It would be awesome if you could make the TP and SL to be trailing instead of fixed percentages.

**Comment by fj317** [comment]
What do you mean by trailing here?

**Comment by ezanchi** [comment]
> What do you mean by trailing here?

By trailing I mean that they maintain certain "distance" in percentage with the real-time price but can only move in one direction (upwards in this case). That way if the price goes up by 10% the TP and SL follow the price, but then if the price goes down they won't move and the TP or the SL will get triggered higher so bigger profit/smaller loss

**Comment by fj317** [comment]
Okay I get what you mean here. So for example, if the price rises 50% then the stop loss value would change from 90% to a value like 110%. 
Yeah I can see how that can be useful although if the price of the coin goes up, then down below the stop loss value (so it triggers the adjusted sell order), then up more than the original peak then you won't make the maximum profit.

**Comment by ezanchi** [comment]
> Okay I get what you mean here. So for example, if the price rises 50% then the stop loss value would change from 90% to a value like 110%.
> Yeah I can see how that can be useful although if the price of the coin goes up, then down below the stop loss value (so it triggers the adjusted sell order), then up more than the original peak then you won't make the maximum profit.

So the proper way to do it is to have 2 more options in the config file where you can set:
TP Trailing True or False
TP Trailing Percentage

Let's give an example:

Buy price was 1000. 
Target price is set to 150%, with Trailing set to True and 10%. 
SL is set to 50%, with Trailing set to True.

If price increases to 1100 (10% increase) then:
Trailing TP does not exist still because Target Price hasn't been achieved.

If then price increases to 1500 then:
Bot will not sell but will place a trailing TP at 10% below price at 1350 (10% less than 1500) that will follow the price **only** up because Target price of 1500 is achieved.

If then price increases to 2000:
Trailing TP will go to 10% below 2000 which is 1800.

If then price goes down to 1900:
Trailing TP will not move and will stay at 1800 because it can only follow **up**.

Price goes to 1800 or below: Trailing TP is triggered and market sell is placed.

**Comment by fj317** [comment]
I don't think this will work as the price usually jumps around a lot during pump & dump events. It might work but again, it's a lot of effort for a feature that most people won't use and will create a lot more bugs for us to deal with.
In the future we may revisit and add the feature but for now, it's nonessential.
