### ISSUE TITLE
Cache Past Trades data for Average Price Calculation

### ISSUE THREAD

**Issue by ezanchi** [fj317/PumpBot#22]
**Describe the solution you'd like**
Have the program pre-download all the needed data for all coins and then every minute update with last minute data and remove first minute data and cache it, so it can calculate the average price faster when the coin is entered instead of downloading it in real-time.

**Comment by fj317** [comment]
Definitely possible and I've thought about this but I think it'll take a long time to download all the necessary data so may not work practically. I'll test it properly soon and see how practically possible doing this is.

**Comment by ezanchi** [comment]
One workaround to speed it up is only download coin that meet certain parameters like low volume and low BTC price and things like that.

Then if coins wasn't cached download it based on the setting in config file.

**Comment by ezanchi** [comment]
What if instead of downloading the whole X last minutes of data we download for X amount of time in milliseconds and calculate the average price with that? It would allow for slow and fast connections to have an average and not be too slow at the same time.

**Comment by ArielKatzir** [comment]
That's a nice idea but I'm pretty sure that the API doesn't have an option to download data in milliseconds, the lowest option is in seconds though I could be wrong. Even so, downloading the data isn't the only thing that might require time. Querying also takes time, especially if done every few milliseconds.

**Comment by ezanchi** [comment]
Yes so what I meant was to download for example during 100 milliseconds whatever data we are able to with our internet speed. I don't mean to download X millions of data, but to download data during Y milliseconds. In the above formula we would control the variable Y

**Comment by ezanchi** [comment]
This is done now and is included in the last Pull, as well as many other corrections and improvements

**Comment by fj317** [comment]
Very nicely done works really well. Thank you! I'll add a permanent mention of you to the readme for all your help.
