### ISSUE TITLE
Invalid API keys

### ISSUE THREAD

**Issue by mopmop682** [fj317/PumpBot#24]
Hi, 

I have since 3 days invlaid api key while everything worked fine I went to see the API management and it is still active how to solve this?

**Comment by skydrow68** [comment]
Maybe try to reinstall all the requirements ?

**Comment by ArielKatzir** [comment]
- Make sure you have an API key with Binance. If you're not sure you can look here: https://www.binance.com/en/my/settings/api-management
- Once you have a key make sure add it to the correct location in the config.json file. 

Thats pretty much all to it

**Comment by skydrow68** [comment]
> * Make sure you have an API key with Binance. If you're not sure you can look here: https://www.binance.com/en/my/settings/api-management
> * Once you have a key make sure add it to the correct location in the config.json file.
> 
> Thats pretty much all to it

For exemple with an invalid API key :


{
    "apiKey": "445f5f5f4sd5f41df54f5f456dsfdffd",
    "apiSecret": "d47f4df55f4df5f5d4f5d6d56",
    "buyLimit": 1.15,
    "profitMargin": 150,
    "percentOfWallet": 50,
    "manualBTC": 0.00000000,
    "stopLoss": 0.90,
    "coinPair": "BTC",
    "getAveragePrice": "FALSE",
    "minutesAveragePrice": "2"
}

**Comment by fj317** [comment]
> Hi,
> 
> I have since 3 days invlaid api key while everything worked fine I went to see the API management and it is still active how to solve this?

Can you give the exact error message that the program gives you so we can narrow down what the problem may be?
If it states 'Invalid Api Key' then you must have entered your Api Key and your Api Secret key incorrectly so check you have the correct values.

**Comment by dodens** [comment]
I have a similar problem - everything works fine on my laptop, but when i run it on PC i'm getting 'invalid api keys' error.

**Comment by fj317** [comment]
> I have a similar problem - everything works fine on my laptop, but when i run it on PC i'm getting 'invalid api keys' error.

This is probably because you haven't included your API keys in the keys.json file when you downloaded the program on your PC.

**Comment by awee1233** [comment]
A BinanceAPI error has occurred. Code = -1013
Invalid quantity.Please use https://github.com/binance/binance-spot-api-docs/blob/master/errors.md to find greater details on error codes before raising an issue.

how to fix it?

**Comment by fj317** [comment]
> 
> 
> A BinanceAPI error has occurred. Code = -1013
> Invalid quantity.Please use https://github.com/binance/binance-spot-api-docs/blob/master/errors.md to find greater details on error codes before raising an issue.
> 
> how to fix it?

Well as the code says the quantity of coin is invalid. 
- Does this happen on the buy or sell order? 
- Please send your config.json settings here so I can see if you've made an error entering your settings.

**Comment by DrTTC** [comment]
I might have a solution. I ran into the same problem just now and ran the following code in cmd as admin (Windows 10):

net stop w32time
w32tm /unregister
w32tm /register
net start w32time
w32tm /resync

Afterwards I noticed that my w32time service isn't started automatically when I turn my PC on. I changed that in the windows service manager, so the problem shouldn't occur again.

**Comment by awee1233** [comment]
> > A BinanceAPI error has occurred. Code = -1013
> > Invalid quantity.Please use https://github.com/binance/binance-spot-api-docs/blob/master/errors.md to find greater details on error codes before raising an issue.
> > how to fix it?
> 
> Well as the error message says the quantity of coin is invalid.
> 
> * Does this happen on the buy or sell order?
> * Please send your config.json settings here so I can see if you've made an error entering your settings.

config.json and key.json are the same as your default repo script

**Comment by dodens** [comment]
> I might have a solution. I ran into the same problem just now and ran the following code in cmd as admin (Windows 10):
> 
> net stop w32time
> w32tm /unregister
> w32tm /register
> net start w32time
> w32tm /resync
> 
> Afterwards I noticed that my w32time service isn't started automatically when I turn my PC on. I changed that in the windows service manager, so the problem shouldn't occur again.
> 
> This might solve a lot of the api errors I have seen on here.

This worked in my case. So i guess it's not a problem with code, but rather with computer.

**Comment by fj317** [comment]
Closing issue since it seems that the original problem has been solved.
