### ISSUE TITLE
bot closing after typing in coin

### ISSUE THREAD

**Issue by ernestonee** [fj317/PumpBot#25]
is it normal that the bot is closing immediatly after typing in the coin?

**Comment by ezanchi** [comment]
> is it normal that the bot is closing immediatly after typing in the coin?

Yes it is normal but I can add a "Press enter to exit" text if @fj317 agrees

**Comment by fj317** [comment]
The bot should open up your web browser page and direct you to the Binance trading pair's market which is why I guess it is closing. The terminal should stay open after it finishes though.

**Comment by ezanchi** [comment]
> The bot should open up your web browser page and direct you to the Binance trading pair's market which is why I guess it is closing. The terminal should stay open after it finishes though.

I guess it depends on how one calls the bot. If called from terminal once the program finishes when it opens Binance website the terminal will stay open. If directly run it will close immediately and no way to check for the info printed.

**Comment by fj317** [comment]
Okay how would you ensure the terminal is kept open if it is directly run?

**Comment by ezanchi** [comment]
> Okay how would you ensure the terminal is kept open if it is directly run?

Adding an input so that it waits for user to press Enter

**Comment by fj317** [comment]
Oh haha sure feel free to implement it.

**Comment by ernestonee** [comment]
if i try open it from terminal it says that there is no file or directory named config.json

**Comment by ernestonee** [comment]
and it doesnt open binance website but i downloaded the newest version

**Comment by ezanchi** [comment]
> if i try open it from terminal it says that there is no file or directory named config.json

Can you send a screenshot please?

**Comment by ernestonee** [comment]
![image](https://user-images.githubusercontent.com/78935127/107947863-5319af80-6f93-11eb-9b5f-857c61605ebe.png)

**Comment by ezanchi** [comment]
Did you download the whole .zip file from GitHub?

**Comment by ernestonee** [comment]
yes i did and the config.json is in the folder

**Comment by ernestonee** [comment]
i try downloading again

**Comment by fj317** [comment]
Not sure if this could be causing the error but have you tried starting the program with 'python3 PumpBot.py' ?

**Comment by ernestonee** [comment]
![image](https://user-images.githubusercontent.com/78935127/107948738-8ad52700-6f94-11eb-8ea3-ddbf113b0dca.png)

**Comment by ezanchi** [comment]
Did you install python Binance library?

**Comment by ernestonee** [comment]
![image](https://user-images.githubusercontent.com/78935127/107949050-f9b28000-6f94-11eb-854b-e8b427e9066f.png)

**Comment by ernestonee** [comment]
yes

**Comment by fj317** [comment]
Go to directory of where you installed the program with CMD. Then use 'python3 PumpBot.py' to start the program.

**Comment by ernestonee** [comment]
it still says no module named binance

**Comment by ernestonee** [comment]
it worked now but without tyoing python 3 just python

**Comment by ernestonee** [comment]
i have another question is the bot limit buying or market buying ?

**Comment by ezanchi** [comment]
Limit buy

> i have another question is the bot limit buying or market buying ?

**Comment by ernestonee** [comment]
But Market buy is better in a pump or?

**Comment by ezanchi** [comment]
> But Market buy is better in a pump or?

Buy market doesn't guarantee that you will not buy the pre-pumped coin. With limit order you will pay a set amount or nothing. You can configure how much overprice you will pay to secure the coin in the config file with the "buyLimit" setting.

**Comment by fj317** [comment]
Feature implemented

> 
> 
> > is it normal that the bot is closing immediatly after typing in the coin?
> 
> Yes it is normal but I can add a "Press enter to exit" text if @fj317 agrees

Now implemented in latest version so closing thread.
Also getting off topic. Please open a new bug report if you continue to have problems.
