### ISSUE TITLE
The relationship of the prices for the orders is not correct.

### ISSUE THREAD

**Issue by fj317** [fj317/PumpBot#29]
I'm getting an error: "The relationship of the prices for the orders is not correct." just before the sell order has been completed. I believe it is something to do with lines 141 & 142 during the OCO order. 
I've tested with BNB, XMR, and LINK so far and all are giving me this error after the buy order has been completed.
Also when I bought LINK I got a MIN_NOTIONAL error which refers to minimum amounts during the buying process which is surprising since I thought this issue was fixed. On my second try it bought it fine which is surprising, and on my third try it completed the entire transaction (buy and sell orders) which is bafferling.

<img width="1187" alt="Screenshot 2021-02-15 at 19 44 53" src="https://user-images.githubusercontent.com/33355293/107987643-49f60600-6fc6-11eb-9e81-7d8dfbe6429a.png">

**Comment by ezanchi** [comment]
Did you manage to fix this?

**Comment by fj317** [comment]
Unsure really, I didn't get it earlier when I tested.
I'll be testing tonight in a proper event so will see whether the bot works as intended or not.

**Comment by fj317** [comment]
I believe I know what is causing this error now
The OCO order must follow the rules [here](https://www.binance.com/en/support/articles/360032605831) that state:
```
Limit price of limit maker order > Market price > Stop price of stop-limit order
```
I didn't quite understand what this meant however I now have an idea.
Basically, the error occurs when the market price is greater than the sell price set. This is occurring in the pumps as the bot buys the coin, then tries to make the OCO order at the price which is dictated by the profit margin. Because the price is jumping around so much, it is possible that the price reaches above the price set out in the OCO order before the OCO order is completed (i.e. in the time between the coins being bought and the coins being sold so roughly lines 200-220.). The API then cannot make the order because the market price is now greater than the limit price which causes the error to occur.

@ezanchi Do you have any ideas to fix this error? Perhaps put a market sell order in the try-catch so if the error occurs it tries to market-sell the coins. Or perhaps try a different type of order all together?

**Comment by fj317** [comment]
I think the trailing stop order will be best after reading the different types of orders that Binance support.

**Comment by fj317** [comment]
It seems neither the python-binance api or the official Binance has an order type that allows for a trailing order to be made so if we wanted to implement this it would have to be a manual implementation.

**Comment by schuesslerf** [comment]
@fj317 I think I'd go with the suggested way to do the sell order in a try catch block and just place a market sell order, when the limit sell order didn't work...

**Comment by fj317** [comment]
> @fj317 I think I'd go with the suggested way to do the sell order in a try catch block and just place a market sell order, when the limit sell order didn't work...

I think I'll do this just to solve this issue however in the long term I'll try and create a trailing stop order function since this seems to be the best type of sell order.

**Comment by fj317** [comment]
> @fj317 I think I'd go with the suggested way to do the sell order in a try catch block and just place a market sell order, when the limit sell order didn't work...

This has now been implemented in latest version. I'll close this issue now since it should be resolved.
