### ISSUE TITLE
 'Client' object has no attribute 'get_avg_price'

### ISSUE THREAD

**Issue by fj317** [fj317/PumpBot#3]
HELP... THX

Traceback (most recent call last):
  File "PumpBot.py", line 39, in <module>
    price = float(client.get_avg_price(symbol=tradingPair)['price'])
AttributeError: 'Client' object has no attribute 'get_avg_price'

_Originally posted by @ducchu68 in https://github.com/fj317/PumpBot/issues/2#issuecomment-778154828_

**Comment by fj317** [comment]
Have you installed and setup the bot correctly as in readme file?
If so please state your OS and any context to the problem.

**Comment by ducchu68** [comment]
win 10 64bit
anaconda3

**Comment by fj317** [comment]
I am unsure what could be causing the error as I'm not getting any type of error myself. Are you using the bot through the command line?

**Comment by ducchu68** [comment]
python PumpBot.py

**Comment by fj317** [comment]
Use python3 rather than python - try that!
