### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by DrTTC** [fj317/PumpBot#32]
1. Open the config.json
2. Change the "minutesAveragePrice" to any non decimal number above 0 (I tried 2, 5, 10, 30 and 60 minutes)
3. Open PumpBot.py
4. Put in the coin to buy (I tried ADA, XLM, LINK...)
5. Get the following error as seen in the picture below

![ZeroDivisionError](https://user-images.githubusercontent.com/65469122/108068293-2f716a80-7062-11eb-9f5e-a9e258985ffb.png)

I have no problems when leaving the number at 0, but this might be a bad idea during a pump. I use the correct API keys and have not changed anything besides the "minutesAveragePrice". Additionally, I use Windows 10 if that's important.

**Comment by ezanchi** [comment]
I will have a look

**Comment by ezanchi** [comment]
I think I found the error. Will push an update and hopefully @fj317 will accept it ASAP.

Meanwhile set it to 0 please.

**Comment by DrTTC** [comment]
Wow, that was fast. Thanks!

**Comment by fj317** [comment]
New version has fixed this by caching the average price of the coins before you enter the coin pair so this parameter is no longer in the code.
