### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by ernestonee** [fj317/PumpBot#34]
when buying some coins im getting list index out of range error

**Comment by fj317** [comment]
Does this occurring on the buying or selling part of the program? Or both?

**Comment by ernestonee** [comment]
Only on the selling part

**Comment by fj317** [comment]
I think this may be related to #29. Specifically the stopPrice and stopLimitPrice parameters in the OCO sell order. I'm trying to fix this bug but it seems very random and is hard to reproduce.

**Comment by dodens** [comment]
I have the same error now, i think it's the line "coinOrderInfo           = order['fills'][0]". 
Now I'm only testing buying, i've commented out  coinPriceBought and coinOrderQty, and i'm getting :
Buy order has been made!
list index out of range

**Comment by fj317** [comment]
Oh I feel like I might have any idea. I believe the problem is occurring because it is sending a limit order and then asking for the quantity bought, however if the limit order hasn't been fulfilled then the error will occur. I believe I might know a fix for this.

**Comment by DrTTC** [comment]
Could this be related to my issue? (#35)

**Comment by fj317** [comment]
> 
> 
> Could this be related to my issue? (#35)

Yes I think these are most likely related. I'll put a fix out and then see if that fixes the problem.

**Comment by fj317** [comment]
Okay I've just pushed a fix for this. Let me know if you're still getting this error or if it has been resolved please!

**Comment by dodens** [comment]
Works fine now.

**Comment by fj317** [comment]
Great! Happy that error is fixed finally.
