### ISSUE TITLE
Bot bought coin, but didn't place sell order

### ISSUE THREAD

**Issue by DrTTC** [fj317/PumpBot#35]
Sometimes when I buy a coin, the buy order is placed as intended, but the sell order somehow doesn't get through. This behaviour is hard to recreate, as it happens randomly. I don't have any error messages to post, as the bot closed itself after typing in the coin.
I use the most recent version of your code, so no trading data has to be downloaded etc.

I just bought ATM during a pump at +10% of the average price, so the buy order was placed. Sadly, no sell order in sight. Any idea on why this is happening? Now I'm sitting on 20€ of useless ATM :(

There is one more thing: My webbrowser didn't open at all, but it should have opened binance and the correct trading pair.

**Comment by ernestonee** [comment]
Did you open the bot via Cmd?

**Comment by DrTTC** [comment]
Yes, but a friend of mine uses the same code and used IDLE. His window also closed immediately and no sell order was placed.

Now, something really interesting happened. The exact same coin was pumped again ($ATM) and now everything worked perfectly. My friend and I both used IDLE now.

**Comment by henyoapps** [comment]
I used it for the second one (wish I knew about the first one, I wouldn't have lost because I wouldn't have bought) and it all worked perfect. Running via cmd as admin.
---
Coin pair: atm
Buy order has been made!
Processing sell order.
Sell order has been made!

Press Enter to Exit...

**Comment by DrTTC** [comment]
I'll try out the new fix tomorrow, there is a smaller pump event announced.

**Comment by DrTTC** [comment]
Bot seems to work great, I'll close this issue.
