### ISSUE TITLE
API servers

### ISSUE THREAD

**Issue by subevilx** [fj317/PumpBot#36]
how can i change binance api servers as on the default server "api.binance.com" i get 200ms while on "api2.binance.com" i get 34 to 30ms

**Comment by fj317** [comment]
I'll look into this.

**Comment by subevilx** [comment]
def getcurprice(symbol):
    apicall = requests.get("https://api2.binance.com/api/v1/ticker/price?symbol=" + pair)
    currentticker = apicall.json()['price']
    ticker = float(currentticker)
    return ticker

**Comment by subevilx** [comment]
here this is from a bot I got from a pump and dump server owner
if u want the full file dm me on discord evil#7070

**Comment by fj317** [comment]
> 
> 
> here this is from a bot I got from a pump and dump server owner
> if u want the full file dm me on discord evil#7070
> the bot is a little broken but u can harvest the code

Pm'ed

**Comment by fj317** [comment]
I've looked into this and I do not think it is really possible to change the API server for all requests made due to the way the python-Binance api is coded.

**Comment by fj317** [comment]
Feature now added so closing issue.
