### ISSUE TITLE
Unable to Buy when I change the Coin Pair

### ISSUE THREAD

**Issue by samkitpalecha** [fj317/PumpBot#41]
Whenever I change the Coin Pair from the Config, the amount doesn't change from BTC to the other Pair. I'm unable to pay from the USDT balance when I select USDT.

**Comment by DrTTC** [comment]
In line 80 you need to change the "asset" parameter from 'BTC' to coinPair (without ' ').

**Comment by fj317** [comment]
I'll fix this now. Thanks for spotting this.

**Comment by fj317** [comment]
Should be fixed now!
