### ISSUE TITLE
error -2010

### ISSUE THREAD

**Issue by subevilx** [fj317/PumpBot#43]
Coin pair: bnb
A BinanceAPI error has occurred. Code = -2010
Account has insufficient balance for requested action.Please use https://github.com/binance/binance-spot-api-docs/blob/master/errors.md to find greater details on error codes before raising an issue.

amount of BTC=13$
BNB=4$
 But still this error 90% of time ill get it no matter what plus im using auto use bnb for fee

**Comment by samsokios** [comment]
i'm getting the same error with 23$ btc but I can't figure out why or how to solve it. I did a previous test with half the amount (11$ ) and it worked to buy but not sell. now with double the amount it won't buy or sell.

**Comment by fj317** [comment]
> i'm getting the same error with 23$ btc but I can't figure out why or how to solve it. I did a previous test with half the amount (11$ ) and it worked to buy but not sell. now with double the amount it won't buy or sell.

This is probably happening because you can't afford the Binance trading fees when you use all of your balance. It is recommend to have a few dollars of BNB to cover Binance trading fees for this reason.

**Comment by fj317** [comment]
> Coin pair: bnb
> A BinanceAPI error has occurred. Code = -2010
> Account has insufficient balance for requested action.Please use https://github.com/binance/binance-spot-api-docs/blob/master/errors.md to find greater details on error codes before raising an issue.
> 
> amount of BTC=13$
> BNB=4$
> But still this error 90% of time ill get it no matter what plus im using auto use bnb for fee

Is this still an issue for you? If not then I'll close this issue.
