### ISSUE TITLE
Market Is Closed

### ISSUE THREAD

**Issue by OKCOOL1233** [fj317/PumpBot#46]
Attempted to place an order as a test several times for ETH then HOT. Worked the first time with ETH, now error is persistent. Nothing bought or sold.

Receiving this error: 

```
A BinanceAPI error has occurred. Code = -1013
Market is closed.Please use https://github.com/binance/binance-spot-api-docs/blob/master/errors.md to find greater details on error codes before raising an issue.

C:\Users\Admin\Desktop\PumpBot-master>
```

**Comment by subevilx** [comment]
servers were down if ur still getting this error recreate a new api
