### ISSUE TITLE
Sell order issue (Code = -1013)

### ISSUE THREAD

**Issue by bouheddadj** [fj317/PumpBot#47]
Hello, I hope you're doing well, First i am so thankful for the bot, I just want to say that there is an issue in selling order, When i type the name of the coin he buy actually but when putting sell order he show the error in the picture below, Please can you help me to slove it ASAP ? Thanks so much, And also if you can improve buy time just a little more it will be great, Thank you again.

![issue 2](https://user-images.githubusercontent.com/79222048/108592309-95653700-736d-11eb-87e2-8b36f11620f9.PNG)

![issue](https://user-images.githubusercontent.com/79222048/108592121-934ea880-736c-11eb-9feb-fdbaeb1ddfb2.PNG)

**Comment by ezanchi** [comment]
I think @fj317 is already fixing it but for the moment try using 85 percentage of your balance or lower

**Comment by bouheddadj** [comment]
Okey great, I appreciate the help, anyway i found a solution to put sell order but i am facing another issue xDDDDDDD, Any solution for it?Look
![issue 3](https://user-images.githubusercontent.com/79222048/108593041-94360900-7371-11eb-856a-8f5c2a36fee4.PNG)

**Comment by fj317** [comment]
I believe I made a mistake when I pushed an update. I'll take a look and try and find a fix for it.

**Comment by bouheddadj** [comment]
Thank you so much, I appreciate the help <3

**Comment by fj317** [comment]
I believe this should be fixed now! Let me know if any other problems occur regarding this issue, otherwise I'll close this issue.
