### ISSUE TITLE
Sell Order was not placed due to decimal rounding

### ISSUE THREAD

**Issue by tank568** [fj317/PumpBot#49]
Hi I know there was a recent change in the tickSize and stepSize and all buying were great but on the selling part I print out the sell quantity for the coin I bought and especially those with long decimals, example I bought 0.5612838 quantity but when placing order it was rounded to 0.57 and so I got the error insufficient balance, it is a known issue I tried to fix it myself but the difference were too far again 0.5612838 and with the solution from this link sometimes it set sell for 0.2 which is far too low compared to 0.5612838

https://github.com/sammchardy/python-binance/issues/91

**Comment by fj317** [comment]
I'll look into this and see if a fix can be found.

**Comment by jbiju94** [comment]
I also faced something similar. 
The error was - 

> A BinanceAPI error has occurred. Code = -1013
> Filter failure: MIN_NOTIONAL. Please use https://github.com/binance/binance-spot-api-docs/blob/master/errors.md to find greater details on error codes before raising an issue.

**Comment by fj317** [comment]
Have you encountered this bug recently or has it fixed itself?

**Comment by AlphaNumeric99** [comment]
Has this been fixed? I am still running into this issue.

**Comment by fj317** [comment]
I have not encountered the error myself at any point so if this error does occur to you, please post the log.txt file here and I'll reopen the issue & take a look.
