### ISSUE TITLE
binance.exceptions.BinanceAPIException: APIError(code=-2010): Account has insufficient balance for requested action.

### ISSUE THREAD

**Issue by Sofficino97** [fj317/PumpBot#5]
Hi, i have this problem, i think when i sell i don't consider fees as i resolve?
![pump](https://user-images.githubusercontent.com/78963013/107768731-341ee180-6d37-11eb-8302-a2e7dc1d914a.PNG)

**Comment by fj317** [comment]
Hi @Sofficino97,
I believe you are right here. I ensure that my wallet always contains some BNB so that this can be used for Binance's fees. 
I'll add a future implement request that checks and makes sure you always have some BNB in your wallet to pay for fees.

**Comment by ducchu68** [comment]
![Screenshot 2021-02-12 202652](https://user-images.githubusercontent.com/52731379/107773818-ca232e00-6d70-11eb-89cf-0cdfe4e3e3a8.png)

**Comment by Sofficino97** [comment]
> Hi @Sofficino97,
> I believe you are right here. I ensure that my wallet always contains some BNB so that this can be used for Binance's fees.
> I'll add a future implement request that checks and makes sure you always have some BNB in your wallet to pay for fees.

hi, thanks its work now. What setting raccomand for pump ?

**Comment by fj317** [comment]
> 
> 
> > Hi @Sofficino97,
> > I believe you are right here. I ensure that my wallet always contains some BNB so that this can be used for Binance's fees.
> > I'll add a future implement request that checks and makes sure you always have some BNB in your wallet to pay for fees.
> 
> hi, thanks its work now. What setting raccomand for pump ?

Well for profit margin this depends on the pump's size, and how much risk you want. The higher the profit margin the more you'll make but the price of the coin must reach this amount. I think 10% per thousand members who are participating in the pump is a good value to go for. But I wouldn't go past 200-300% profit unless you're expecting a huge pump.
Percent of wallet is up to you.
Buy limit I'd recommend 0 (so turn off the feature) unless you have good internet as the bot will need to download A LOT of data which slows it down.
Stop loss I'd put at 80-95% - again its up to you.
Coin pair will be BTC.

You should do lots of research before each pump to ensure you are thoroughly confident in what will happen.

**Comment by skydrow68** [comment]
Binance can't use BTC for the fees ? Is it mendatory to buy BNB for the fees ?

**Comment by fj317** [comment]
You can use BTC I believe however using BNB gives you a discount on your fees. See [here](https://www.binance.com/en/support/articles/115000429332-Fee-Structure-on-Binance).
The reason the bot gave an error was because (I'd assume) they were using 100% of their wallet funds which means there was no BTC left to pay the 0.1% transaction fee.

**Comment by skydrow68** [comment]
Okay : With 100% they didn't buy 
But : If i put 50% of my wallet, i have that : it's buying but we dont have the sell order : 
To precise : 50% of the wallet represent in this case 60$ of BTC

Buy order has been made!
Traceback (most recent call last):
  File "PumpBot.py", line 88, in <module>
    order = client.create_oco_order(
  File "/home/yannick/.local/lib/python3.8/site-packages/binance/client.py", line 1456, in create_oco_order
    return self._post('order/oco', True, data=params)
  File "/home/yannick/.local/lib/python3.8/site-packages/binance/client.py", line 240, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/home/yannick/.local/lib/python3.8/site-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/yannick/.local/lib/python3.8/site-packages/binance/client.py", line 197, in _request
    return self._handle_response()
  File "/home/yannick/.local/lib/python3.8/site-packages/binance/client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-2010): Account has insufficient balance for requested action.

**Comment by skydrow68** [comment]
precision : we tried that with 200 of profit margin. We tried with 110 and it was working. Is that normal ?

**Comment by fj317** [comment]
I don't know why it would work with 150 and not 200 - it sounds like some kind of weird bug but I have no idea what could cause that.
If possible could you add the following lines just before the sell order has been made (on line 86):
print(coinOrderQty)
print(roundedPriceToSell)
print(float_to_string(stopLoss * coinPriceBought, int(- math.log10(minPrice))))

These should print the values for the order and might tell you what it happening.

**Comment by skydrow68** [comment]
Coin pair: doge
Buy order has been made!
1197.0
0.00000288
0.00000072
Traceback (most recent call last):
  File "PumpBot.py", line 92, in <module>
    order = client.create_oco_order(
  File "/home/yannick/.local/lib/python3.8/site-packages/binance/client.py", line 1456, in create_oco_order
    return self._post('order/oco', True, data=params)
  File "/home/yannick/.local/lib/python3.8/site-packages/binance/client.py", line 240, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/home/yannick/.local/lib/python3.8/site-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/yannick/.local/lib/python3.8/site-packages/binance/client.py", line 197, in _request
    return self._handle_response()
  File "/home/yannick/.local/lib/python3.8/site-packages/binance/client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-2010): Account has insufficient balance for requested action.

**Comment by fj317** [comment]
or it could still the original problem of not having any coin to pay for selling fee that Binance imposes.

**Comment by skydrow68** [comment]
* i have 4$ in BNB for the fee

**Comment by fj317** [comment]
Can you check on https://www.binance.com/en/my/dashboard to ensure you have 'Using BNB to pay for fees ( 25% discount )' ticked?

**Comment by skydrow68** [comment]
it's not ticked because it wasn't working too ^^

**Comment by fj317** [comment]
So once ticked, is the bot now buying and creating the sell orders correctly?

**Comment by skydrow68** [comment]
![Capture](https://user-images.githubusercontent.com/39465988/107808800-6e55a680-6d6a-11eb-8887-988e7c4dced5.PNG)

i dont understand... i have 10$ in BNB

**Comment by fj317** [comment]
Well Binance doesn't seem to think you have? You mustn't have bought it correctly.

**Comment by skydrow68** [comment]
![ff](https://user-images.githubusercontent.com/39465988/107809101-de642c80-6d6a-11eb-9000-83694cccf166.PNG)
humm

**Comment by henyoapps** [comment]
Does the bot define how many coins when purchasing? Or is it just give me whatever you can with x amount of BTC? In other words, is it asking to purchase a set amount of coins?

**Comment by henyoapps** [comment]
I checked the code, and it is sending a limit order in. what I was thinking about the 'insufficient' issue is probably not it. I've also tested the latest commit with a but on BNB, and it showed as a limit order

**Comment by fj317** [comment]
> 
> 
> ![ff](https://user-images.githubusercontent.com/39465988/107809101-de642c80-6d6a-11eb-9000-83694cccf166.PNG)
> humm

This is an issue with Binance I'd recommend you **asking their support channels**. In the screenshot you sent previously you can see in the top right that it says you have 0 BNB whereas the screenshot you just sent it says you have ~0.1 BNB.

**Comment by fj317** [comment]
> 
> 
> I checked the code, and it is sending a limit order in. what I was thinking about the 'insufficient' issue is probably not it. I've also tested the latest commit with a but on BNB, and it showed as a limit order

The bot gets the current market price of the coin pair, then works out how much of the coin it can buy using the allocated BTC. It then completes the order by making a limit order at the given price for the amount of coin calculated.

**Comment by skydrow68** [comment]
> > ![ff](https://user-images.githubusercontent.com/39465988/107809101-de642c80-6d6a-11eb-9000-83694cccf166.PNG)
> > humm
> 
> This is an issue with Binance I'd recommend you **asking their support channels**. In the screenshot you sent previously you can see in the top right that it says you have 0 BNB whereas the screenshot you just sent it says you have ~0.1 BNB.

![Capture](https://user-images.githubusercontent.com/39465988/107811763-f9d13680-6d6e-11eb-9fb1-d74090608c61.PNG)

okay this is good. I try also if this is working now

**Comment by skydrow68** [comment]
![Capture d’écran du 2021-02-12 20-17-56](https://user-images.githubusercontent.com/39465988/107812111-7f54e680-6d6f-11eb-9176-dcaa7d1221ca.png)
Yeeeeees thank you !

**Comment by henyoapps** [comment]
> > I checked the code, and it is sending a limit order in. what I was thinking about the 'insufficient' issue is probably not it. I've also tested the latest commit with a but on BNB, and it showed as a limit order
> 
> The bot gets the current market price of the coin pair, then works out how much of the coin it can buy using the allocated BTC. It then completes the order by making a limit order at the given price for the amount of coin calculated.
> It uses a limit order (rather than a market buy) to avoid yourself buying coins that are being pre-pumped.
> Also the error that @skydrow68 is experiencing is to do with the fees around the sell-order which is an OCO order.

alright. sorry for hijacking the thread, just trying to help, and thought I had a reason for that happening.

**Comment by fj317** [comment]
> 
> 
> > > I checked the code, and it is sending a limit order in. what I was thinking about the 'insufficient' issue is probably not it. I've also tested the latest commit with a but on BNB, and it showed as a limit order
> > 
> > 
> > The bot gets the current market price of the coin pair, then works out how much of the coin it can buy using the allocated BTC. It then completes the order by making a limit order at the given price for the amount of coin calculated.
> > It uses a limit order (rather than a market buy) to avoid yourself buying coins that are being pre-pumped.
> > Also the error that @skydrow68 is experiencing is to do with the fees around the sell-order which is an OCO order.
> 
> alright. sorry for hijacking the thread, just trying to help, and thought I had a reason for that happening.

No problemo I welcome alternate solutions to problems :)
