### ISSUE TITLE
Invalid trading pair

### ISSUE THREAD

**Issue by pump-maker** [fj317/PumpBot#52]
**Describe the bug**
The program runs well, until I have to input the coin pair, because once I do this appears 

"""Coin pair: BTC_USDT
Invalid trading pair given. Check your input is correct as well as config.json's 'coinPair' value to fix the error.""

I have tried to use symbols such as %,$,&,/,(,) and even space but none seem to work, and when I go to config.json it doesnt appear anything saying "coinPair". Im I missing some step? Or do I have to use different symbols?

My desktop is a IOS X using VisualStudioCode to run the program

**Comment by fj317** [comment]
The term in config.json was renamed to quotedCoin and I forgot to update the coin name references in the code so sorry about that, I'll fix it in my next push.
Valid trading pairs would be something like BNBBTC - to use this trading air you'd input just 'BNB' in the program and set quotedCoin in config.json to 'BTC'. The trading pair are the coins that you are trading in. This is quite simple research so I'd highly recommend you to research more before you lose money using the bot incorrectly.

**Comment by pump-maker** [comment]
When I text it now it appears this

A BinanceAPI error has occurred. Code = -1013
Invalid quantity.. Please use https://github.com/binance/binance-spot-api-docs/blob/master/errors.md to find greater details on error codes before raising an issue.

I dont have any money on BTC rn, is that the problem?

**Comment by fj317** [comment]
Yes.

**Comment by ArielKatzir** [comment]
Yes.
