### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by goofysmurf** [fj317/PumpBot#53]
**Describe the bug**

**To Reproduce**
1. Rename key.json.example. to key.json.
2. Enter my API key between the ""
3. Enter my API Secret between the ""
4. Invalid API Key.
5. Generated a new key.
6. Still get the same error.

**Expected behavior**
Invalid API KEY
API Key Works on another bot.

**Desktop (please complete the following information):**
 - OS: Windows 10 Python 3.8

**Comment by ezanchi** [comment]
If it says Invalid API key then you are most likely pasting it wrong.

**Comment by goofysmurf** [comment]
Thats the exact code below , dont worry the API key is deleted already.

kindly advise where my error is ?

{
    "apiKey": "P9ujJWKWiuVPMGyCZimEN7vXWKfMZ2nND81X5bktvrbvoNqLsmblsvoJJvrVpbyl",
    "apiSecret": "GvE2yH0zm0FFd1JeiEnoTGPpERpWO6D6jXO4XINTbagGlLcGkc08SYewvubvvhek"
}

**Comment by goofysmurf** [comment]
Python binance was installed as  well.

**Comment by ezanchi** [comment]
Are you from US?

**Comment by goofysmurf** [comment]
South Africa

**Comment by ezanchi** [comment]
Are you connecting to Binance.com?

**Comment by goofysmurf** [comment]
IS this just valid for US binance ? That would explain the issue then.

**Comment by ezanchi** [comment]
Do you have the latest version? 1.1 I believe it is

**Comment by ezanchi** [comment]
> IS this just valid for US binance ? That would explain the issue then.

Not its the other way. Its compatible with EU Binance

**Comment by ezanchi** [comment]
> Thats the exact code below , dont worry the API key is deleted already.
> 
> kindly advise where my error is ?
> 
> {
> "apiKey": "P9ujJWKWiuVPMGyCZimEN7vXWKfMZ2nND81X5bktvrbvoNqLsmblsvoJJvrVpbyl",
> "apiSecret": "GvE2yH0zm0FFd1JeiEnoTGPpERpWO6D6jXO4XINTbagGlLcGkc08SYewvubvvhek"
> }

Honestly the keys seem normal. Maybe @fj317 can shine some light to this?

**Comment by goofysmurf** [comment]
Got a non US binance account and use a bot with the API keys perfectly fine.

I installed it by running pip install python-binance so it must be the latest. Installed the bot in a separate folder.

**Comment by ezanchi** [comment]
> Got a non US binance account and use a bot with the API keys perfectly fine.
> 
> I installed it by running pip install python-binance so it must be the latest. Installed the bot in a separate folder.

So did you already fix it?

**Comment by goofysmurf** [comment]
Thanks for trying to assist. I am quite stumped its pretty straight forward the install. Confirmed if I exclude the API keys it does complain about missing keys. Thus it looks like its parsing it. 

Maybe something I did wrong with python-binance ?

**Comment by ezanchi** [comment]
I am not fully understanding what the current status of the issue is.

**Comment by goofysmurf** [comment]
Il boot into linux and see if I can reproduce the issue with a install there.

**Comment by goofysmurf** [comment]
Ok user error, my local time was out of sync with Binance. Its working fine now, I am sorry that I wasted your time...
