### ISSUE TITLE
Setting 100% profit

### ISSUE THREAD

**Issue by tank568** [fj317/PumpBot#54]
Hi is there a way to set profitMargin 100%? I tried putting 200 it will throw error BinanceAPIException: APIError(code=-1013): Filter failure: PERCENT_PRICE
Thank you

**Comment by fj317** [comment]
I am not getting this error. Can you give more details as well as give your config.json parameters please?

**Comment by tank568** [comment]
No I was just setting 100% profit e.g. profitMargin: 150 = 50% profit isn't, so if I thought if wanted 100% profit I put 200 for profitMargin and that's how I got the error

**Comment by fj317** [comment]
Yes that's correct. I'll check if I get an error but it's surprising that you're getting one. Can you give the exact error message ?

**Comment by fj317** [comment]
Did this ever fix itself or is it still buggy?

**Comment by Arceus786** [comment]
that is no bug. U have to have ur btc over 0.0001. In other words. U have to invest at least 0.0001 btc in order to use the pump.

**Comment by bru53001** [comment]
I think that's a Binance API limitation as every other bot has some trouble with profit targets above 100%.
