### ISSUE TITLE
A BinanceAPI error has occurred. Code = -1013 Invalid quantity.

### ISSUE THREAD

**Issue by NSDevelopment** [fj317/PumpBot#55]
A BinanceAPI error has occurred. Code = -1013
Invalid quantity.. Please use https://github.com/binance/binance-spot-api-docs/blob/master/errors.md to find greater details on error codes before raising an issue.

I tried all of branch but I'm getting this error. What should I do ?

**Comment by esasiyunx** [comment]
how did you fix?
