### ISSUE TITLE
It bought but does not sell

### ISSUE THREAD

**Issue by NSDevelopment** [fj317/PumpBot#56]
Coin pair: ada
Buy order has been made!
Processing sell order.
A BinanceAPI error has occurred. Code = -2010
The relationship of the prices for the orders is not correct.. Please use https://github.com/binance/binance-spot-api-docs/blob/master/errors.md to find greater details on error codes before raising an issue.

I always get this kind of error. It buys well but does not sell even I made margin 100.0001.

    "quotedCoin": "BTC",
    "buyLimit": 1.10,
    "percentOfWallet": 50,
    "manualQuoted": 0.00000000,
    "profitMargin": 100.001,
    "stopLoss": 0.90,
    "endpoint": "default", 

I made like this to try whether it works or not.

**Comment by fj317** [comment]
This error #29 is known and I am unable to find a solution for it as I don't understand why/what is causing the error.

**Comment by fj317** [comment]
This should now be fixed. Closing issue.
