### ISSUE TITLE
Discord/Telegram Text scrapper

### ISSUE THREAD

**Issue by bouheddadj** [fj317/PumpBot#59]
Hello, I hope you're doing so well, Please, We would be thankful and happy if you implement text scrapper, I know some groups realese it on image but most do text, They use bots that scrap text too, that why they won't change to images, Please can you implement that ? Thanks so much in advance.

**Comment by fj317** [comment]
This has been suggested [before](https://github.com/fj317/PumpBot/issues/50#issue-812838441) and I still believe the same reasons I set out there stand.
