### ISSUE TITLE
KuCoin support?

### ISSUE THREAD

**Issue by goodguypete** [fj317/PumpBot#60]
Hey, thanks for a great bot. Would it be possible to use it with KuCoin's api? I've seen that in some other outdated python bot.
Also about the pre-pump detection, that would be an awesome and a must-have function considering how scummy some P&D groups are, i've heard it's also possible to do in python. Thanks again.

**Comment by fj317** [comment]
I've spoken about Kucoin support before (#57) and I don't have the time available to spend on recreating the bot to work for the Kucoin api. Pre-pump detection has been mentioned before as well ( #12) however it is a huge undertaking and like I said I don't have the time to implement it right now.
