### ISSUE TITLE
Invalid keys

### ISSUE THREAD

**Issue by eganmcc** [fj317/PumpBot#64]
1 .pip install python-binance ->Done
2. modify the config,json ->Done
3. modify and rename to keys.json with the correct Binance API (triple checked)
4. python3 PumpBot.py
5. Invalid API Keys
6. repeat #3 with a new key which work with other exchange 
7. Invalid API keys

Any idea or help?

**Comment by fj317** [comment]
This is very strange its happened a few times with different people however I don't know whats linking these issues. Are you sure you're creating the API keys correctly with the right settigns enabled?

**Comment by eganmcc** [comment]
i used the existing api keys that works for other exchanges and also created a new one but they all failed BUT i just tried to run it just now and this time it works? did binance close their API before a pump which happened around the same time when I was having the Invalid API Keys issue?

**Comment by fj317** [comment]
Hm that is weird, could just be an error on Binance's part with creating keys. I'll close this issue, if the problem persists I'll reopen it.

**Comment by eganmcc** [comment]
i have some more info, because I was having an issue on my windows machine i ran the bot on my mac and it was having the same issue.

I just tried it a couple minutes ago on the mac and the problem still happening so i compared the both the config and keys the only difference is on the pc config the endpoint is set to api3 so i replaced default to api3 in the mac config and it works

The confusing part is when i set it back to default it still works with both my mac and pc so i'm not sure if that api3 is the key to "jump start" the api to binance or there;s still something else

I thought i;d share this and thanks for your quick response

**Comment by fj317** [comment]
Hm that is weird seems like a problem with Binance but I have no idea what could be causing it. Guess it fixed if you use api3 as your endpoint.
