### ISSUE TITLE
Invalid API Keys with all versions

### ISSUE THREAD

**Issue by samkitpalecha** [fj317/PumpBot#69]
I think there has been some change with Binance keys, but I've been getting Invalid API keys since some time now. 
![image](https://user-images.githubusercontent.com/36188758/110849291-13658f80-82d5-11eb-8eea-42de348a819b.png)

**Comment by schuesslerf** [comment]
Are you sure, you set the keys correctly and you created them correctly as well? For me, its working fine..

**Comment by samkitpalecha** [comment]
Yeah for being sure, I created new ones too but the same error is appearing.

**Comment by schuesslerf** [comment]
and you got the newest version? did u remove the " by any chance in keys file?

**Comment by fj317** [comment]
The bot seems to work fine for me as well.
The bot is failing at getting your balance for your quoted coin (which should be BTC). Maybe the value of quotedCoin has been changed in config.json?

**Comment by PhyTom** [comment]
I also get the same error today, yesterday it was working fine and I didn't change anything

**Comment by PhyTom** [comment]
Now I've switched to the last version and the error code became: "Error with getting balance"

**Comment by fj317** [comment]
Its weird that its failing with getting your balance but not with getting the coin data. Have you checked in config.json you haven't changed the value for quotedCoin by accident?

**Comment by PhyTom** [comment]
I've found that running the code on visual studio and deleating the condition to get the error you wrote, I get this as the answer:
Exception has occurred: BinanceAPIException
APIError(code=-1021): Timestamp for this request was 1000ms ahead of the server's time.
  File "C:\Users\Tommaso il grande\Desktop\Bot modificato\PumpBot.py", line 91, in <module>
    QuotedBalance = float(client.get_asset_balance(asset=quotedCoin)["free"])

**Comment by fj317** [comment]
This is an error with your computer rather than the pc. See the main readme for a thread that has more help to fix this error.

**Comment by samkitpalecha** [comment]
Hi, 
I'm having this issue: 
![image](https://user-images.githubusercontent.com/36188758/111081278-86b30f80-8528-11eb-9403-3dbde5e8ff6e.png)
Also, here is the screenshot of config.json:
![image](https://user-images.githubusercontent.com/36188758/111081338-d72a6d00-8528-11eb-9cf6-1fca712b6031.png)

**Comment by fj317** [comment]
Try changing the endpoint to a different one since this seems to be a problem with you connecting to Binance.

**Comment by PhyTom** [comment]
I solved the problem by synching the time in the windows option menu before opening the bot, i've found my time goes out of sync with Binance of about a second every 24hr.

**Comment by fj317** [comment]
Hm interesting glad you got it fixed!
