### ISSUE TITLE
Automatic coin detection

### ISSUE THREAD

**Issue by schuesslerf** [fj317/PumpBot#70]
Hey mate,

in addition to the pre pump detection (like checking on binance on "unnatural activities", it might be really cool, if you could e.g. insert a telegram channel and it automatically reads the coin and buys it afterwards. 
This would save some time again, as 1. I think that the bot might get the telegram message a little bit earlier, before displayed on the client, but especially because it'd save about 1-2 seconds again and I think we all know, that 1-2 seconds matter a lot in a pump...
If telegram is not an option, lots of pumps are also posted on discord, maybe thats easier? I know that for both telegram and discord, there are python apis....

You think that's a good implementation?

**Comment by fj317** [comment]
This has been suggested before #50 and I believe the reasons I set out there still stand. Additionally, this would take alot of time to implement and the logic required to read and decipher the correct coin name would be difficult since lots of servers release the coin as an image with dummy coins to prevent this exact thing. Eg:
![A3S5II3AU43F3I8](https://user-images.githubusercontent.com/33355293/111029888-15277400-83f7-11eb-9e7f-abc9a2177c8f.png)

**Comment by schuesslerf** [comment]
For those having little coding knowledge and might want to implement this themselves..

```
from telethon import TelegramClient, events, sync
import re

# Remember to use your own values from my.telegram.org!
api_id = 123456789
api_hash = 'xxxxxxxxxxxxxxxxxxxxxxx'
client = TelegramClient('nameless', api_id, api_hash)

@client.on(events.NewMessage(chats='mygroup'))
async def my_event_handler(event):
    text = event.raw_text
    print(text)

client.start()
client.run_until_disconnected()
```

I basically just implemented this where you need to enter the coin yourself... I then used a regular expression to get the coin (in my case, it's always posted the same, something like #ABC as, so I just use the regex to get that and remove the #, passing that coin to the next function... 
From what I've tried: It seems like the api prints the message about 100-200ms earlier then you can see it in your telegram... Then I'd calculate about 1 - 2 seconds for checking the message and entering the coin in the bot... So in total it's something about 1,5 -2 seconds that you can save with that and from what I've experienced so far, this can be really import 2 seconds...

So if you get the pumps from a group in telegram, which always uses the same syntax, you can use this code and just insert the regex to get the coin pretty easily :)

**Comment by rayures** [comment]
> So if you get the pumps from a group in telegram, which always uses the same syntax, you can use this code and just insert the regex to get the coin pretty easily :)

tnx. having some challenges with python and regex. Any way we can discus this further somewhere?

**Comment by raulbalestra** [comment]
same here, if you could create a quick video showing us how exactly you implemented this code to the current bot, or raise a new Pull request with this new feature implemented that would be very cool.

**Comment by schuesslerf** [comment]
Still testing it to make sure it works fine, if I got it working perfectly, I'll give you some hints on that or just submit a pull request

**Comment by rayures** [comment]
Tnx for the reply. I got it working :-). Ran multiple bots the last pump.
Absolutely no python / telethon experience, so I do not know if it is a proper / fast implementation.

**Comment by raulbalestra** [comment]
@rayures, Are you able to create a pull request with this new feature?

**Comment by rayures** [comment]
> @rayures, Are you able to create a pull request with this new feature?

Hi, a pull request would not be accepted by fj317 (see arguments) and the code limits the bot to telegram scouting only. 
i have a branch with Telegram Scouting: https://github.com/rayures/PumpBot/tree/tg_scouting you can try it. 

note: add TG info in keys.json and config.json. First start it creates a TG sessionfile, so TG authentication is necessary. You can create multiple bots when the botname is unique. The TG group/channel name must match the t.me/CHANNELNAME
