### ISSUE TITLE
Sell Orders not created during a pump. 

### ISSUE THREAD

**Issue by samsokios** [fj317/PumpBot#71]
I have noticed that when a pump starts when I first input the coin name the bot will keep producing the same message (waiting for coin to buy...)

Almost always, the coin ends up being bought almost instantly and at a fairly low price but no sell orders are created and the bot doesn't update further

**Comment by fj317** [comment]
> no sell orders are created and the bot doesn't update further

What does the bot output when this happens?

**Comment by samsokios** [comment]
It outputs only this line

Waiting for coin to buy...

it keeps outputting this multiple times (~100?)

then nothing further, no update once the buy order has been completed and no sell order issued

**Comment by fj317** [comment]
Okay I've added more logging now to the bot so if this happens again please send the log.txt file so we can see exactly what is happening.

**Comment by N3KRoN** [comment]
I think its all from this:

# waits until the buy order has been confirmed 
while order['status'] != "FILLED":
    print("Waiting for coin to buy...")


This function check value in dict order named status and nothing any more. Dict doest updated and we have infinite loop.

**Comment by fj317** [comment]
Good spot I'll query the order information and update the dictionary value to stop this loop.

**Comment by N3KRoN** [comment]
> Hmm it could be but I thought the order dictionary values automatically updated themselves with the order information after it had been fulfilled.

Need every time check that orders "FILLED" or "BUY" that now all orders selled.

https://github.com/sammchardy/python-binance/blob/f153d8651e91d67c0c125f3bb78d397edae0ab64/binance/client.py#L1674-L1713



Realize from another bot on github:
`def sell(self, symbol, quantity, orderId, sell_price, last_price):

        '''
        The specified limit will try to sell until it reaches.
        If not successful, the order will be canceled.
        '''

        buy_order = Orders.get_order(symbol, orderId)

        if buy_order['status'] == 'FILLED' and buy_order['side'] == 'BUY':
            #print('Buy order filled... Try sell...')
            self.logger.info('Buy order filled... Try sell...')
        else:
            time.sleep(self.WAIT_TIME_CHECK_BUY_SELL)
            if buy_order['status'] == 'FILLED' and buy_order['side'] == 'BUY':
                #print('Buy order filled after 0.1 second... Try sell...')
                self.logger.info('Buy order filled after 0.1 second... Try sell...')
            elif buy_order['status'] == 'PARTIALLY_FILLED' and buy_order['side'] == 'BUY':
                #print('Buy order partially filled... Try sell... Cancel remaining buy...')
                self.logger.info('Buy order partially filled... Try sell... Cancel remaining buy...')
                self.cancel(symbol, orderId)
            else:
                self.cancel(symbol, orderId)
                #print('Buy order fail (Not filled) Cancel order...')
                self.logger.warning('Buy order fail (Not filled) Cancel order...')
                self.order_id = 0
                return

        sell_order = Orders.sell_limit(symbol, quantity, sell_price)`

**Comment by kuratkull** [comment]
Why is it giving a lower purchase order than the instant coin price? Do you have the same problem?
Waiting for coin to buy... 
This is because the order placed has a value lower than the current value. how can we fix this.  can not catch the price per second.

**Comment by kuratkull** [comment]
`
averagePrice = 0
for ticker in averagePrices:
    if ticker["symbol"] == tradingPair:
        averagePrice = ticker["wAvgPrice"]
# if average price fails then get the current price of the trading pair (backup in case average price fails)
if averagePrice == 0: averagePrice = float(client.get_avg_price(symbol=`

**It is necessary to buy at the current price of the trading pair, not the average price.**

**Comment by fj317** [comment]
If you want to purchase the coin at a higher price increase your buyLimit parameter. The program buys at the average price to avoid pre-pumped coins, however it will buy the coin at the price UP TO whatever your buy limit parameter is set to. Eg if buyLimit is 1.5 then it will set limit order for the coin at a price 1.5 times the average price.
