### ISSUE TITLE
unsupported operand float and list

### ISSUE THREAD

**Issue by Flappyflap** [fj317/PumpBot#72]
**[Describe the bug]**
After entering a coin and pressing enter it shows the below output.

Traceback (most recent call last):
  File "C:\Crypto\PumpBot-master\PumpBot.py", line 162, in <module>
    amountOfCoin = AmountToSell / averagePrices
TypeError: unsupported operand type(s) for /: 'float' and 'list'

**To Reproduce**
1. python3 PumpBot.py
2. Wait for it to connect
3. Enter your chosen coin (I was testing on the coin "one".

**Expected behavior**
Order being placed and then sell depending on profit or loss.

**Screenshots**
![image](https://user-images.githubusercontent.com/80651877/111086654-3f6f5380-8515-11eb-8b77-d36e958a0cc6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 - 64 BIT

**Additional context**
Tried removing and then downloading again, same issue.

**Update**
Just to update, I had to make two changes:
1. Incase "ticker["wAvgPrice"]" inside of a float.
2. Change the calculation for amount of coin from averagePrices to averagePrice.
 
Just tested and working without issue now.
Unsure if it is something wrong my side or code side, if it's something I did wrong or didn't install, please let me know :)

**1**
"for ticker in averagePrices:
    if ticker["symbol"] == tradingPair:
        averagePrice = **float(ticker["wAvgPrice"])**
if averagePrice == 0: averagePrice = price"

**2**
amountOfCoin = AmountToSell / **averagePrice**

**Comment by Flappyflap** [comment]
**Update**
Just to update, I had to incase "ticker["wAvgPrice"]" inside of a float. Just tested and working without issue now. Unsure if it is something wrong my side or code side, if it's something I did wrong or didn't install, please let me know :)

"for ticker in averagePrices:
    if ticker["symbol"] == tradingPair:
        averagePrice = **float(ticker["wAvgPrice"])**
if averagePrice == 0: averagePrice = price"

**Comment by fj317** [comment]
I think this is a mistake I left in my code after not testing it properly. I'll do a fix for it.

**Comment by Flappyflap** [comment]
No problem and just want to say a big thanks to yourself, ezanchi and ariel. So far it has been working really well.

**Comment by fj317** [comment]
Just pushed a fix for this. Let me know if any other errors occur!
