### ISSUE TITLE
i'm getting an -1013 error

### ISSUE THREAD

**Issue by esasiyunx** [fj317/PumpBot#73]
no problem when i want to use 50% of my money but it gives this error when i want to use all of my money

can you help me asap.

ss is attached ;

https://ibb.co/525H1db
https://ibb.co/NWhSTH5

OS: Windows 10

**Comment by fj317** [comment]
Could be an error with rounding perhaps. Try with something like 95% of your money and see if that works. If it does then the program is probably rounding the quantity up which is causing the error.

**Comment by esasiyunx** [comment]
It happens when I try with 85% of my money, I should be able to use 100% of my money. Can you fix this?

**Comment by esasiyunx** [comment]
TypeError: unsupported operand type(s) for /: 'float' and 'str'

im gettings this error 

amountOfCoin =  AmountToSell / averagePrice

on this code, can you help me?

**Comment by DrTTC** [comment]
I changed averagePrice to float(averagePrice), worked for me

**Comment by fj317** [comment]
I've pushed a fix for this let me know if this is resolved.

**Comment by kuratkull** [comment]
https://ibb.co/LrPwxmz
https://ibb.co/2P9sP0q  %85
https://ibb.co/Bn5k29j %95
https://ibb.co/m4jStWL % 100

When I set it to btc it shows the amount correctly.
but I get a transaction error -1003 on each of them.



Which line did you make the correction?

> I changed averagePrice to float(averagePrice), worked for me

**Comment by kuratkull** [comment]
"buylimit" : 2.5,  i have done    _**"A BinanceAPI error has occurred. Code = -2010"**_ error code appears.

**Comment by kuratkull** [comment]
worked for a while, I did not do anything only bought 5 CHZ :(

**Comment by kuratkull** [comment]
the error has been fixed.
