### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'float' and 'str'

### ISSUE THREAD

**Issue by DrTTC** [fj317/PumpBot#74]
**Describe the bug**

Traceback (most recent call last):
  File "C:\Users\Dragan Totic\AppData\Local\Programs\Python\Python39\BinanceBot\PumpBot-master\PumpBot.py", line 163, in <module>
    amountOfCoin = AmountToSell / averagePrice
TypeError: unsupported operand type(s) for /: 'float' and 'str'

**To Reproduce**
1. Use USDT as coin pair (at least I used USDT)
2. Use percentOfWallet or manualQuoted - doesn't matter
3. Try to buy any coin - doesn't change anything

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by DrTTC** [comment]
Fixed it for myself by changing 

"amountOfCoin = AmountToSell / averagePrice"

to

"amountOfCoin = AmountToSell / float(averagePrice)"

**Comment by fj317** [comment]
Thanks for giving your fix. I'll add it into the code now.
