### ISSUE TITLE
Running in ubuntu

### ISSUE THREAD

**Issue by sabbathin** [fj317/PumpBot#79]
After a lot of work i got it working under ubuntu 20.4, but after 1.4 i've had no luck, could anyone share the earlsiesta version with me?  Thanks

**Comment by fj317** [comment]
What sort of error messages are you getting? It should work fine with Ubuntu.

**Comment by sabbathin** [comment]
Thank you, everything needs to be installed as su or sudo **on the same directory**, and I mean EVERYTHING needed by pumpbot :D

**Comment by sabbathin** [comment]
running smooth now
