### ISSUE TITLE
Error with getting balance

### ISSUE THREAD

**Issue by LaDice** [fj317/PumpBot#80]
I did all the necessary steps to run the PumpBot but when I try to give the command python3 PumpBot.py
I get this:  Caching all BTC pairs average prices...
                
               This can take a while. Please , be patient...
                
                Sucessfully catchedBTCpairs!
                Error with getting balance.

**Comment by fj317** [comment]
This could have happened if you changed the value of the quotedCoin in config.json to an invalid value. If its a valid coin (like BTC) then perhaps try changing your endpoint (change it from default to api1 and see if it works. It could be an error with Binance rather than the program.

**Comment by LaDice** [comment]
Tried all those APIs... same error

**Comment by fj317** [comment]
I have no idea what could be causing this. If you manage to solve  it, please update this issue with the solution.

**Comment by kuratkull** [comment]
Have you checked the api key and api secret? I got the same error when I wrote to check the binance spot test api.

**Comment by LaDice** [comment]
I use the production API key and secret from the live environment in Binance,there is no test. (the API keys have no errors)

**Comment by bhav1kmaru** [comment]
any solutions?

**Comment by LaDice** [comment]
Unfortunately No. I tried my best, I need help from the owner.

**Comment by sabbathin** [comment]
Investing amount for BTC: 0.00526173
Investing amount in USD: 294.95

Coin pair: hive
A BinanceAPI error has occurred. Code = -2010
Account has insufficient balance for requested action.. Please use https://github.com/binance/binance-spot-api-docs/blob/master/errors.md to find greater details on error codes before raising an issue.

**Comment by eternaldreamz** [comment]
I have the following error:

Caching all BTC pairs average prices...
This can take a while. Please, be patient...

Sucessfully cachedBTCpairs!
Error with getting balance.
Press any key to continue . . .

**Comment by nikos69** [comment]
same error as per LaDice and eternaldreamz above.

**Comment by nikos69** [comment]
I looked at the spec https://python-binance.readthedocs.io/en/latest/_modules/binance/client.html#Client.get_asset_balance and compared with the code in PumpBot.py and it looks fine to me. I wonder if there is sth wrong with the Binance API. Alternatively, I am wondering if is there another method the code can call to get the asset (=quotedCoin) balance through the Binance API...or may be a combination that the balance can be derived.....

**Comment by sabbathin** [comment]
well their js does actually work, does etics apply if we pythonize it? https://github.com/BinaryDevil/binance-pump-bot

**Comment by fj317** [comment]
> I have the following error:
> 
> Caching all BTC pairs average prices...
> This can take a while. Please, be patient...
> 
> Sucessfully cachedBTCpairs!
> Error with getting balance.
> Press any key to continue . . .

I really don't know why you're getting an error honestly. I'm testing it on my end and its working fine. Could be an issue with Binance. Have you tried recreating your keys or trying a different endpoint?

**Comment by nikos69** [comment]
Good news fj317. You are spot on!!! I changed the API key and secret and now IT WORKS!!! I believe because I was using the same API keypair (key & secret) in other software API calls, somehow the BINANCE API didn't like it which is a mystery to me unless they are doing it for security purposes.
I am glad is sorted. thank you again fj317.

**Comment by fj317** [comment]
I'm glad it's fixed for you ! :)

**Comment by fj317** [comment]
Closing issue since there seems to be a solution for it now
