### ISSUE TITLE
Error with getting balance.

### ISSUE THREAD

**Issue by ariez4999** [fj317/PumpBot#83]
Hi, currently i'm having this issue. Am i did something wrong?

Caching all BNB pairs average prices...
This can take a while. Please, be patient...

Sucessfully cached BNB pairs!
Error with getting balance.

**Comment by fj317** [comment]
This is an issue with your API keys I think. Try recreating your API keys or changing the endpoint that the bot connects to.

**Comment by ariez4999** [comment]
Hi, it's me again. Sorry for the delayed replies. Tried to :- 
- recreate API keys
- changing endpoint
- changing coin pairs

Still runs into the following errors..

Caching all USDT pairs average prices...
This can take a while. Please, be patient...

Sucessfully cached USDT pairs!
Error with getting balance.
Quitting, this could take a few seconds!
>>>

**Comment by ariez4999** [comment]
log.txt as following. I'm using the latest Python btw, thanks again!

23:24:09 --- Loading API keys.
23:24:09 --- API keys successfully loaded.
23:24:09 --- Loading config.json settings.
23:24:09 --- config.json settings successfully loaded.
23:24:11 --- Caching all quoted coin pairs.
23:24:11 --- Sucessfully cached quoted coin pairs.
23:24:11 --- Getting quoted balance amount.
23:24:12 --- Error with getting balance.
23:24:12 --- Quitting program

**Comment by fj317** [comment]
This is weird because the program is using your API keys to cache all the coins that are pairs of BTC however its failing with getting your balance. The steps you said you tried are exactly what I would do myself to solve this issue so I'm unsure what to advise you. Could be an issue with python, are you running with python3 command ? If you are then it seems to be a problem with Binance but I'm not completely sure.

**Comment by ghostrox** [comment]
Has anyone found a solution to this..running into the same issue..

**Comment by percyparedes** [comment]
I have the same problem. At first i was able to start the bot but now i get the same problem. However it works on ubuntu on the same pc and on windows on a different pc

**Comment by fj317** [comment]
I've just pushed some code that will log the exact error that's causing the issue. If you try and report back what the error message given in log.txt is then this may help solve this problem.

**Comment by ghostrox** [comment]
First of all thanks for all your work..
Will definitely try it and report back

**Comment by ariez4999** [comment]
> I've just pushed some code that will log the exact error that's causing the issue. If you try and report back what the error message given in log.txt is then this may help solve this problem.

Hi, did another try and went these errors. Also no logs were written to the provided text file.

Caching all USDT pairs average prices...
This can take a while. Please, be patient...

Sucessfully cached USDT pairs!
Checking BNB balance if topup required.
Topping up BNB wallet to avoid transaction fees
Traceback (most recent call last):
  File "C:\Users\8F3QPP1\Downloads\PumpBot-master\PumpBot-master\PumpBot.py", line 185, in <module>
    topupBNB(0.01, 0.02)
  File "C:\Users\8F3QPP1\Downloads\PumpBot-master\PumpBot-master\PumpBot.py", line 44, in topupBNB
    order = client.order_market_buy(symbol=balancePair, quantity=qty)
  File "C:\Users\8F3QPP1\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 1366, in order_market_buy
    return self.order_market(**params)
  File "C:\Users\8F3QPP1\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 1338, in order_market
    return self.create_order(**params)
  File "C:\Users\8F3QPP1\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 1200, in create_order
    return self._post('order', True, data=params)
  File "C:\Users\8F3QPP1\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 240, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "C:\Users\8F3QPP1\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\8F3QPP1\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 197, in _request
    return self._handle_response()
  File "C:\Users\8F3QPP1\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1013): Filter failure: MIN_NOTIONAL

**Comment by fj317** [comment]
> 
> 
> > I've just pushed some code that will log the exact error that's causing the issue. If you try and report back what the error message given in log.txt is then this may help solve this problem.
> 
> Hi, did another try and went these errors. Also no logs were written to the provided text file.
> 
> Caching all USDT pairs average prices...
> This can take a while. Please, be patient...
> 
> Sucessfully cached USDT pairs!
> Checking BNB balance if topup required.
> Topping up BNB wallet to avoid transaction fees
> Traceback (most recent call last):
> File "C:\Users\8F3QPP1\Downloads\PumpBot-master\PumpBot-master\PumpBot.py", line 185, in
> topupBNB(0.01, 0.02)
> File "C:\Users\8F3QPP1\Downloads\PumpBot-master\PumpBot-master\PumpBot.py", line 44, in topupBNB
> order = client.order_market_buy(symbol=balancePair, quantity=qty)
> File "C:\Users\8F3QPP1\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 1366, in order_market_buy
> return self.order_market(**params)
> File "C:\Users\8F3QPP1\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 1338, in order_market
> return self.create_order(**params)
> File "C:\Users\8F3QPP1\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 1200, in create_order
> return self._post('order', True, data=params)
> File "C:\Users\8F3QPP1\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 240, in _post
> return self._request_api('post', path, signed, version, **kwargs)
> File "C:\Users\8F3QPP1\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 202, in _request_api
> return self._request(method, uri, signed, **kwargs)
> File "C:\Users\8F3QPP1\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 197, in _request
> return self._handle_response()
> File "C:\Users\8F3QPP1\AppData\Local\Programs\Python\Python39\lib\site-packages\binance\client.py", line 230, in _handle_response
> raise BinanceAPIException(self.response)
> binance.exceptions.BinanceAPIException: APIError(code=-1013): Filter failure: MIN_NOTIONAL
Please read #86 and find answers on how to fix MIN_NOTIONAL errors.

**Comment by ariez4999** [comment]
Hi, it's me again. Tried using the manual quoted from config.json, it buys only using 10 usdt and gives errors as following:

Caching all USDT pairs average prices...
This can take a while. Please, be patient...

Sucessfully cached USDT pairs!
Checking BNB balance if topup required.
 
 ___                                ___           _   
(  _`\                             (  _`\        ( )_ 
| |_) ) _   _   ___ ___   _ _      | (_) )   _   | ,_)
| ,__/'( ) ( )/' _ ` _ `\( '_`\    |  _ <' /'_`\ | |  
| |    | (_) || ( ) ( ) || (_) )   | (_) )( (_) )| |_ 
(_)    `\___/'(_) (_) (_)| ,__/'   (____/'`\___/'`\__)
                         | |                          
                         (_)                          

Investing amount for USDT: 25
Investing amount in USD: 1566062.75

Coin pair: VET
Waiting for coin to buy...
Buy order has been made!
Processing sell order.
A BinanceAPI error has occurred. Code = -1013
Filter failure: MIN_NOTIONAL Please use https://github.com/binance/binance-spot-api-docs/blob/master/errors.md to find greater details on error codes before raising an issue.
Market selling due to error
Sold at market price
Quitting, this could take a few seconds!

**Comment by ariez4999** [comment]
Found that there is no error code -1013 from the links. Thanks again
