### ISSUE TITLE
CommandNotFoundException

### ISSUE THREAD

**Issue by erreffe** [fj317/PumpBot#84]
Hi, I tried to install everything and test the bot and everything worked. While now I have this problem and I can't understand why.

In riga:1 car:1
+ PumpBot.py
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (python3PumpBot.py:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by bru53001** [comment]
I'm not the repository owner but I think your error here is not leaving a space between python3 and PumpBot.py, that is a Powershell error. If it still doesn't work, try python or py instead.

**Comment by erreffe** [comment]
Thanks for the reply. 

The problem is with powershell but even if I use phyton or if I also leave the space between phyton3 and pumpbot.py the error repeats. 

it's a very strange mistake that he didn't give me before. 

I am going crazy

**Comment by erreffe** [comment]
> Thanks for the reply.
> 
> The problem is with powershell but even if I use phyton or if I also leave the space between phyton3 and pumpbot.py the error repeats.
> 
> it's a very strange mistake that he didn't give me before.
> 
> I am going crazy



> I'm not the repository owner but I think your error here is not leaving a space between python3 and PumpBot.py, that is a Powershell error. If it still doesn't work, try python or py instead.

Thanks for the reply.

The problem is with powershell but even if I use phyton or if I also leave the space between phyton3 and pumpbot.py the error repeats.

it's a very strange mistake that he didn't give me before.

I am going crazy

**Comment by bru53001** [comment]
Are you writing "phyton"? That's not how "python" is spelled.

**Comment by erreffe** [comment]
> Are you writing "phyton"? That's not how "python" is spelled. Try each of these in the file directory of the script:
> 
> ```
> py PumpBot.py
> python PumpBot.py
> python3 PumpBot.py
> ```
> 
> If you still can't get it to work, try reinstalling Python and tick add to PATH during the installation.


I had tried all the syntaxes but hadn't tried "py PumpBot.py". With this it works, thank you very much for your availability and for solving the problem.
