### ISSUE TITLE
A BinanceAPI error has occurred. Code = -1013

### ISSUE THREAD

**Issue by raulbalestra** [fj317/PumpBot#86]
**Describe the bug**
I could not use the app yet, after installing and configuring everything as described in the read-me I've got an error message when I tried to buy a specific coin.

The only change I made was in the config.json file.

**{
    "quotedCoin": "USDT",
    "buyLimit": 1.15,
    "percentOfWallet": 50,
    "manualQuoted": 0,
    "profitMargin": 150,
    "stopLoss": 0.90,
    "endpoint": "default",
    "comment": "DO NOT EDIT ANYTHING BELOW THIS LINE",
    "currentVersion" : 1.8
}**

As you can see above the quotedCoin is now **USDT** and manualQuoted is **0**.
Error message:

Coin pair: XRP
**A BinanceAPI error has occurred. Code = -1013
Filter failure: MIN_NOTIONAL. Please use https://github.com/binance/binance-spot-api-docs/blob/master/errors.md to find greater details on error codes before raising an issue.
Quitting, this could take a few seconds!
rbalestra@### PumpBot %** 

I've found the issue, in the error.md list however, I could not find any information on how to fix this.

Could you please let me know what can I do to fix it?

Best Regards,

Raul Balestra

**Comment by bru53001** [comment]
Not the creator but MIN_NOTIONAL means your order is below the minimum permitted size. If your USDT balance is less than 20,  this will happen since the minimum USDT order size is 10, and 50% of anything less than 20 will be less than 10.

**Comment by fj317** [comment]
Min_notational errors occur because the quantity multiplied by the price doesn't reach the minimum amount for Binance. This could be caused if you are buy a small quantity (less than $5).

**Comment by raulbalestra** [comment]
Guys, thank you very much for the prompt response! It's working now.
