### ISSUE TITLE
Unable to set a lower % profit or lower stop loss

### ISSUE THREAD

**Issue by raulbalestra** [fj317/PumpBot#89]
Hello folks,

Sorry for the stupid questions, but I'm unable to set a lower %, by default the profitMargin value is 150 (50%), correct me if I'm wrong, (100%) of this profit margin value supposed to be 300, hence (10%) supposed to be 30. However, when I put a value lower than 150, it crashed the system with an error message.

The same occurs if I change the stopLoss value, at the moment it's equivalent to 10%, but if I wanna set a lower value of stop loss, like 3% or so, I also get the same error message, how can I solve this issue?

h1. error message
`Coin pair: AAVEDOWN
A BinanceAPI error has occurred. Code = -1013
Filter failure: MIN_NOTIONAL. Please use https://github.com/binance/binance-spot-api-docs/blob/master/errors.md to find greater details on error codes before raising an issue.
Quitting, this could take a few seconds!`

`{
    "quotedCoin": "USDT",
    "buyLimit": 1.15,
    "percentOfWallet": 50,
    "manualQuoted": 0,
    "**profitMargin": 30,**
    "stopLoss": 0.10,
    "endpoint": "default",
    "comment": "DO NOT EDIT ANYTHING BELOW THIS LINE",
    "currentVersion" : 1.8
}`

BR
Raul Balestra

**Comment by kuratkull** [comment]
Code = -1013 Filter failure: MIN_NOTIONAL
You are ordering less than the minimum amount. check your balance and try again.

**Comment by raulbalestra** [comment]
This is not a balance issue man, that's the thing, when I set the values for the default the bot works fine.

**Comment by fj317** [comment]
Your profit margin 30 is too low. It starts at 100 so if you wanted a 30% increase enter 130 to the config file. 
As mentioned above, MIN_NOTIONAL errors mean the price * quantity is too low. Could be because your balance is too small, or by the profitMargin being 30.

**Comment by raulbalestra** [comment]
thanks, it's working fine now!
