### ISSUE TITLE
Is there any possibility to connect the bot to a telegram Group?

### ISSUE THREAD

**Issue by raulbalestra** [fj317/PumpBot#91]
Hello folks,

I've had another idea, is it possible to connect the bot to this Telegram group?

Group: https://t.me/whalebotpumps

If it could happen we could set the bot to auto buy and sell the coin based on the signals we get in this group, not sure if it's feasible but would be brillhant.

BR

Raul Balestra

**Comment by fj317** [comment]
Its possible but as mentioned before Telegram groups usually give the coin pair as an image with dummy coins in it to ensure bots can't read directly from the telegram groups. Therefore this feature won't really work. See further details #50.
