### ISSUE TITLE
Big Issue!

### ISSUE THREAD

**Issue by wp3030** [fj317/PumpBot#93]
I tried the bot. The buy order entered correctly but the sell order did not enter. Here is the mistake he gave me:

```
Buy order has been made!
Processing sell order.
Traceback (most recent call last):
  File "C:\Users\utente\AppData\Local\Programs\Python\Python39\Scripts\PumpBot-master\PumpBot.py", line 284, in <module>
    coinOrderInfo = order["fills"][0]
IndexError: list index out of range
```

Can you help me? It could be very dangerous if it happened to others. Failing to sell could result in you losing all your money

My PC: Windows10, Python 3.9.4

**Comment by fj317** [comment]
Can you send your config.json and give more details on what caused the problem? Thanks.

**Comment by wp3030** [comment]
{
    "quotedCoin": "BTC",
    "buyLimit": 1.15,
    "percentOfWallet": 50,
    "manualQuoted": 0.00000000,
    "profitMargin": 140,
    "stopLoss": 0.90,
    "endpoint": "default",





    "comment": "DO NOT EDIT ANYTHING BELOW THIS LINE",
    "currentVersion" : 1.8
}

**Comment by wp3030** [comment]
everything ok, I tried a second test and now it works.
