### ISSUE TITLE
Some bugs and the solutions I've found

### ISSUE THREAD

**Issue by Agustin-Bulzomi** [fj317/PumpBot#94]
**Description**

1) When executing the code, the line "f =  open("keys.json", )" throws the error:
"FileNotFoundError: [Errno 2] No such file or directory: 'keys.json'."

_Solution:_ I've changed the line to specify the address: "f = open("C:\Program Files\Python\Python38\PumpBot\keys.json", )"
This happened afterwards with the config file, and the solution was the same.

2) Afterwards, the code couldn't find the API Keys:

"Traceback (most recent call last):
  File "C:\Program Files\Python\Python38\PumpBot\PumpBot.py", line 141, in <module>
    bm.start_user_socket(process_message)
  File "C:\Program Files\Python\Python38\lib\site-packages\binance\websockets.py", line 714, in start_user_socket
    user_listen_key = self._client.stream_get_listen_key()
  File "C:\Program Files\Python\Python38\lib\site-packages\binance\client.py", line 2650, in stream_get_listen_key
    res = self._post('userDataStream', False, data={}, version=self.PRIVATE_API_VERSION)
  File "C:\Program Files\Python\Python38\lib\site-packages\binance\client.py", line 323, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "C:\Program Files\Python\Python38\lib\site-packages\binance\client.py", line 265, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Program Files\Python\Python38\lib\site-packages\binance\client.py", line 260, in _request
    return self._handle_response()
  File "C:\Program Files\Python\Python38\lib\site-packages\binance\client.py", line 313, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-2015): Invalid API-key, IP, or permissions for action."

_Solution:_ I've configured the Binance API to use any IP address (I had it configured to use only mine)

3) Finally, the code said:

"Account has insufficient balance for requested action."

_Solution:_ I've changed "percentOfWallet" from 100 to 80

------------------------------------------------------------------------------------------------------------------------------------------

**Desktop:**
 
- OS: Windows 10. updated as of 23th of April

------------------------------------------------------------------------------------------------------------------------------------------

**Additional context**

I've installed Python in Program Files because I always have problems when using the default directory that runs through Users. This is because my name has an accent that generates loads of errors (child mistake, it was years ago).

**Comment by fj317** [comment]
Thanks for posting the solutions for the problems you've encountered, they'll be useful for others if they come across these errors.
I'll close this issue now unless you have any other bugs to report.
