### ISSUE TITLE
Binance app

### ISSUE THREAD

**Issue by Agustin-Bulzomi** [fj317/PumpBot#95]
It would be awesome if the code could open Binance's Windows or iOS program instead of the browser, if one wants to. I'm sure it can be done changing the "webbrowser" line so it executes the .exe but then it would have to open the pair and I don't see a URL configuration for it.

**Comment by RohitKonge** [comment]
@Agustin-Bulzomi Does the pump bot work during the PUMP and DUMP?

**Comment by Agustin-Bulzomi** [comment]
@RohitKonge I haven't tried it yet

**Comment by fj317** [comment]
I don't believe this is really possible since I can't see a way to open the .exe and go directly to the trading pair. Closing issue.
